spring:
  application:
    name: lockIn-backend
  profiles:
    active: dev

server:
  port: 8080

jwt:
  secret: /Gt7+Oqe2oIz5s+8gAaaf7vuKf7K9Qgp5kMc6vrzZ3g=
  expiration: 90000

cookie:
  expiration: 106400
