spring:
  datasource:
    url: jdbc:postgresql://db:5432/appdb
    username: ${DB_USER:appuser}
    password: ${DB_PASSWORD:apppass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect