spring:
  application:
    name: lockIn-backend
  profiles:
    active: dev

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:your-default-secret-key-if-not-found}
  expiration: ${JWT_EXPIRATION:8000}

cookie:
  secret: ${COOKIE_SECRET:your-default-secret-key-if-not-found}
  expiration: ${COOKIE_EXPIRATION:9000000}
